spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: product-code-service
          uri: http://product-code-service:8081
          predicates:
            - Path=/api/product-codes/**
          filters:
            - StripPrefix=1
        - id: medication-service
          uri: http://medication-service:8082
          predicates:
            - Path=/api/medications/**,/api/medication-types/**
          filters:
            - StripPrefix=1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG