spring:
  application:
    name: product-code-service
  datasource:
    url: jdbc:h2:file:/data/productcode-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: always  # Para ejecutar data.sql al iniciar

server:
  port: 8081
  servlet:
    context-path: /product-codes

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
    com.mbsoft: DEBUG
    org.hibernate.SQL: DEBUG