spring:
  application:
    name: medication-service
  datasource:
    url: jdbc:h2:mem:medicationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

server:
  port: 8082

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics